package hibernate.mappings;
// Generated Aug 26, 2016 4:43:40 AM by Hibernate Tools 4.3.1



/**
 * RioSport generated by hbm2java
 */
public class RioSport  implements java.io.Serializable {


     private Integer id;
     private Sport sport;

    public RioSport() {
    }

    public RioSport(Sport sport) {
       this.sport = sport;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sport getSport() {
        return this.sport;
    }
    
    public void setSport(Sport sport) {
        this.sport = sport;
    }




}


