package hibernate.mappings;
// Generated Aug 26, 2016 4:43:40 AM by Hibernate Tools 4.3.1



/**
 * RioSportDiscipline generated by hbm2java
 */
public class RioSportDiscipline  implements java.io.Serializable {


     private Integer id;
     private SportDiscipline sportDiscipline;

    public RioSportDiscipline() {
    }

    public RioSportDiscipline(SportDiscipline sportDiscipline) {
       this.sportDiscipline = sportDiscipline;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public SportDiscipline getSportDiscipline() {
        return this.sportDiscipline;
    }
    
    public void setSportDiscipline(SportDiscipline sportDiscipline) {
        this.sportDiscipline = sportDiscipline;
    }




}


