package hibernate.mappings;
// Generated Aug 26, 2016 4:43:40 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * SportDiscipline generated by hbm2java
 */
public class SportDiscipline implements java.io.Serializable
{

    private Integer id;
    private Sport sport;
    private String name;
    private Integer minPlayers;
    private Integer maxPlayers;
    private String disciplineType;
    private Set<RioSportDiscipline> rioSportDisciplines = new HashSet<RioSportDiscipline>(0);
    private Set<SportsmanDiscipline> sportsmanDisciplines = new HashSet<SportsmanDiscipline>(0);

    public SportDiscipline()
    {
    }

    public SportDiscipline(Sport sport, String name, Integer minPlayers, Integer maxPlayers, String disciplineType, Set<RioSportDiscipline> rioSportDisciplines, Set<SportsmanDiscipline> sportsmanDisciplines)
    {
	this.sport = sport;
	this.name = name;
	this.minPlayers = minPlayers;
	this.maxPlayers = maxPlayers;
	this.disciplineType = disciplineType;
	this.rioSportDisciplines = rioSportDisciplines;
	this.sportsmanDisciplines = sportsmanDisciplines;
    }


    @Override
    public boolean equals(Object o)
    {
	return ((SportDiscipline)o).id.intValue() == id.intValue();
    }

    @Override
    public int hashCode()
    {
	int hash = 5;
	hash = 31 * hash + Objects.hashCode(this.id);
	return hash;
    }
    
    public Integer getId()
    {
	return this.id;
    }

    public void setId(Integer id)
    {
	this.id = id;
    }

    public Sport getSport()
    {
	return this.sport;
    }

    public void setSport(Sport sport)
    {
	this.sport = sport;
    }

    public String getName()
    {
	return this.name;
    }

    public void setName(String name)
    {
	this.name = name;
    }

    public Integer getMinPlayers()
    {
	return this.minPlayers;
    }

    public void setMinPlayers(Integer minPlayers)
    {
	this.minPlayers = minPlayers;
    }

    public Integer getMaxPlayers()
    {
	return this.maxPlayers;
    }

    public void setMaxPlayers(Integer maxPlayers)
    {
	this.maxPlayers = maxPlayers;
    }

    public String getDisciplineType()
    {
	return this.disciplineType;
    }

    public void setDisciplineType(String disciplineType)
    {
	this.disciplineType = disciplineType;
    }

    public Set<RioSportDiscipline> getRioSportDisciplines()
    {
	return this.rioSportDisciplines;
    }

    public void setRioSportDisciplines(Set<RioSportDiscipline> rioSportDisciplines)
    {
	this.rioSportDisciplines = rioSportDisciplines;
    }

    public Set<SportsmanDiscipline> getSportsmanDisciplines()
    {
	return this.sportsmanDisciplines;
    }

    public void setSportsmanDisciplines(Set<SportsmanDiscipline> sportsmanDisciplines)
    {
	this.sportsmanDisciplines = sportsmanDisciplines;
    }

}
