package hibernate.mappings;
// Generated Aug 26, 2016 4:43:40 AM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Sportsman generated by hbm2java
 */
public class Sportsman implements java.io.Serializable
{

    private Integer id;
    private Country country;
    private Sport sport;
    private String firstName;
    private String lastName;
    private Set<SportsmanDiscipline> sportsmanDisciplines = new HashSet(0);
    private Team team;
    private Set<Competition> competitions = new HashSet(0);
    private String sex;

    public Sportsman()
    {
    }

    public Sportsman(Country country,
	    Sport sport,
	    String firstName,
	    String lastName,
	    Set<SportsmanDiscipline> sportsmanDisciplines,
	    Team team,
	    String sex)
    {
	this.country = country;
	this.sport = sport;
	this.firstName = firstName;
	this.lastName = lastName;
	this.sportsmanDisciplines = sportsmanDisciplines;
	this.team = team;
	this.sex = sex;
    }
    
    @Override
    public boolean equals(Object o)
    {
	Sportsman s = (Sportsman)o;
	if (s.getId() == null || getId() == null)
	    return false;
	return ((Sportsman)o).getId().intValue() == getId().intValue();
    }

    @Override
    public int hashCode()
    {
	int hash = 5;
	hash = 17 * hash + Objects.hashCode(this.id);
	return hash;
    }

    public Set<Competition> getCompetitions()
    {
	return competitions;
    }

    public void setCompetitions(Set<Competition> competitions)
    {
	this.competitions = competitions;
    }
    
    public Integer getId()
    {
	return this.id;
    }

    public void setId(Integer id)
    {
	this.id = id;
    }

    public Country getCountry()
    {
	return this.country;
    }

    public void setCountry(Country country)
    {
	this.country = country;
    }

    public Sport getSport()
    {
	return this.sport;
    }

    public void setSport(Sport sport)
    {
	this.sport = sport;
    }

    public String getFirstName()
    {
	return this.firstName;
    }

    public void setFirstName(String firstName)
    {
	this.firstName = firstName;
    }

    public String getLastName()
    {
	return this.lastName;
    }

    public void setLastName(String lastName)
    {
	this.lastName = lastName;
    }

    public Set<SportsmanDiscipline> getSportsmanDisciplines()
    {
	return this.sportsmanDisciplines;
    }

    public void setSportsmanDisciplines(Set<SportsmanDiscipline> sportsmanDisciplines)
    {
	this.sportsmanDisciplines = sportsmanDisciplines;
    }

    public Team getTeam()
    {
	return team;
    }

    public void setTeam(Team team)
    {
	this.team = team;
    }

    public String getSex()
    {
	return sex;
    }

    public void setSex(String sex)
    {
	this.sex = sex;
    }

}
