package hibernate.mappings;
// Generated Aug 26, 2016 4:43:40 AM by Hibernate Tools 4.3.1

import java.util.*;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable
{

    private Integer iduser;
    private Country country;
    private String username;
    private String password;
    private String name;
    private String surname;
    private String email;
    private String type;
    private Set<Competition> competitions = new HashSet(0);
    private Boolean approved = false;

    public User()
    {
    }

    public User(String username, String password, String name, String surname, String email, String type)
    {
	this.username = username;
	this.password = password;
	this.name = name;
	this.surname = surname;
	this.email = email;
	this.type = type;
    }

    public User(Country country, String username, String password, String name, String surname, String email, String type)
    {
	this.country = country;
	this.username = username;
	this.password = password;
	this.name = name;
	this.surname = surname;
	this.email = email;
	this.type = type;
    }

    public Integer getIduser()
    {
	return this.iduser;
    }

    public void setIduser(Integer iduser)
    {
	this.iduser = iduser;
    }

    public Country getCountry()
    {
	return this.country;
    }

    public void setCountry(Country country)
    {
	this.country = country;
    }

    public String getUsername()
    {
	return this.username;
    }

    public void setUsername(String username)
    {
	this.username = username;
    }

    public String getPassword()
    {
	return this.password;
    }

    public void setPassword(String password)
    {
	this.password = password;
    }

    public String getName()
    {
	return this.name;
    }

    public void setName(String name)
    {
	this.name = name;
    }

    public String getSurname()
    {
	return this.surname;
    }

    public void setSurname(String surname)
    {
	this.surname = surname;
    }

    public String getEmail()
    {
	return this.email;
    }

    public void setEmail(String email)
    {
	this.email = email;
    }

    public String getType()
    {
	return this.type;
    }

    public void setType(String type)
    {
	this.type = type;
    }

    public Set<Competition> getCompetitions()
    {
	return competitions;
    }

    public void setCompetitions(Set<Competition> competitions)
    {
	this.competitions = competitions;
    }

    public Boolean getApproved()
    {
	return approved;
    }

    public void setApproved(Boolean approved)
    {
	this.approved = approved;
    }
}
